# Define only required parameters here.
# Other parameters such as version, copyright, publisher, pages, are taken from Implementation Guide in input folder.

# id: ihe.ro.xrts
canonical: https://profiles.ihe.net/RO.XRTS
name: IHEROXRTS
status: draft
# version: 0.0.2
fhirVersion: 4.0.1
FSHOnly: true
dependencies:
    hl7.fhir.us.core: 3.1.0
    hl7.fhir.us.mcode: 
      id: mcode
      uri: http://build.fhir.org/ig/HL7/fhir-mCODE-ig
      version: current
    hl7.fhir.us.codexrt: 
      id: codexrt
      uri: http://build.fhir.org/ig/HL7/codex-radiation-therapy
      version: current